**출처**
- [Do it! 자바 프로그래밍 입문](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791163030195)
- [https://www.nowwatersblog.com/cs/Exception](https://www.nowwatersblog.com/cs/Exception)
- [https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html](https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html)
- [https://read-write-developer.tistory.com/121?category=819503](https://read-write-developer.tistory.com/121?category=819503)
- [https://youn12.tistory.com/32](https://youn12.tistory.com/32)
- [https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC](https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
- [https://dololak.tistory.com/61](https://dololak.tistory.com/61)
---

**학습할것(필수)**

- Exception과 Error의 차이는?
- 자바가 제공하는 예외 계층 구조
- RuntimeException과 RE가 아닌 것의 차이는?
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 커스텀한 예외 만드는 방법

---
<br>

### 1. Exception과 Error의 차이는?
**Error**

하드웨어의 오작동 또는 고장으로 인해 응용프로그램에 이상이 생겼거나 JVM 실행에 문제가 생겼을 경우 발생한다.

- 프로그램에서 제어 할 수 없다.
- Error 클래스의 하위 클래스는 시스템에서 발생하는 오류를 다루며, 프로그램에서 제어하지 않는다.
- Error 발생 시 프로그램은 비정상적으로 종료된다.
- EX) 사용 가능한 동적 메모리가 없는 경우, 스택 메모리의 오버플로 발생

**Exception**

사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류
- 프로그램에서 제어 할 수 있다.
- 보통 프로그램 실행 중 발생
- EX) 프로그램에서 파일을 읽어 사용하려는데 파일이 없는 경우, 네트워크로 데이터를 전송하려는데 연결이 안 된 경우, 배열 값을 출력하려는데 배열 요소가 없는 경우

<br>

### 2. 자바가 제공하는 예외 계층 구조
Exception과 Error는 Throwable을 상속한다.

![image](https://user-images.githubusercontent.com/26623547/104831615-f6f93800-58cd-11eb-9682-e192bab57851.png)

**Error**
- Error 클래스와 하위 클래스들이 속한다. 예상 할 수 없고 복구 할수 없다.

Exception은 `Checked Exception`과 `UnChecked Exception`으로 나뉜다.

**1. Checked Exception**
###### Exception의 하위 클래스 중 RuntimeException을 제외한 모든 Exception
- `컴파일 시점에 발생 하는 예외이다.`
  - try-catch 또는 throws를 통해 처리를 해줘야 컴파일이 된다.

**2. UnChecked Exception**
###### RuntimeException을 상속받은 Exception
- `컴파일 시점에 확인되지 않는 예외이다.`
  - 발생을 예측할 수 없고, 복구할 수 없는 예외

<br>

### 3. RuntimeException과 RE가 아닌 것의 차이는?

**RuntimeException**은 `Checked Exception`과 `UnChecked Exception`을 구분하는 기준이다.

Exception의 자식 클래스 중 RuntimeException을 제외한 모든 Exception은 Checked Exception이며,
RuntimeException클래스와 자식들은 UnChecked Exception이다.


<br>

### 4. 자바에서 예외 처리 방법

**try영역** 
- 실행 코드 영역

**catch영역**
- try에서 Exception 발생 시 처리 코드 영역
- 예외 발생 시 JVM이 예외 객체를 만들어 catch영역으로 던진다. catch에서는 해당 예외객체와 변수를 선언해주어야 한다.

**throw**
- 강제로 예외를 발생 시키는 키워드

**throws**
- 예외가 발생한 함수를 호출한 함수에게 던진다.
- try-catch구문이나 throws를 사용하지 않으면 JVM이 해당 예외를 처리한다.

**finally**
- try-catch문에서 예외가 발생하건 안하건 catch가 실행되건 안하건 무조건 실행된다.
- 보통 리소스 정리 및 파일 close에 사용

**꼭 필요한 곳에서만 예외처리 사용!**
> 일반적으로 try구문 안에서의 코드가 try밖에 위치한 코드보다 느리다고 한다.

<br>
---

**1. 기본 try-catch**
```java
class test {
  void Exception() {
    try {
        //실행 코드
    } catch (Exception1 ex1) {
        //Exception1 처리 코드
    } catch (Exception2 ex2) {
        //Exception2 처리 코드
    }
  }
}
```

<br>

**2. finally**

try-catch 과정에서 어떤 예외 상황이 발생해도 반드시 finally 영역이 실행 된다.
```java
class test {
  void Exception() {
    try {
        //실행 코드
    } catch (Exception1 ex1) {
        //Exception1 처리 코드
    } finally {
        //반드시 실행되는 코드
    }
  }
}
```

<br>

**※예외문에서 return 사용 시 주의점**
- finally 블록 내에 문장은 try, catch 블록에 return문이 있더라도 실행 된다.
- try 블록에서의 return 
  - try 리턴값 리턴
- catch 블록에서의 return 
  - catch 리턴값 리턴
- finally 블록에서의 return
  - try-catch에서 Exception이 발생을 해도 return의 제어권은 finally가 가져오게 된다. 오류인 상황이 발생을 해야 하지만 정상적으로 값이 전달 된 것으로 처리.
  - 위와 같은 경우 때문에 finally에서 return을 사용하면 안됨(Anti Pattern)
  

<br>

**3. Multicatch block**
- 자바 7부터 catch block을 합칠 수 있다.
- 다수의 Exception을 하나의 로직으로 처리할 수 있다.

**주의점**
- multicatch block으로 묶인 예외는 부모-자식 관계에 있으면 안된다.
  - 자식 클래스로 잡아낼 수 있는 예외는 부모클래스로도 잡아낼 수 있기 떄문에 사실상 중복 된 것 
- multicatch block에 사용된 예외들의 공통된 조상의 멤버만 사용 할 수 있다.
  - 해당 변수가 어느 예외 인지 판단 할수 없기때문에, instanceo로 체크, 형변환 후 사용 해야 한다. 
```java
class test {
  void Exception(){
        try {
            // 실행 코드
        }catch (Exception1 | Exception2 | Exception3 exception){
            // Exception1, Exception2, Exception3 예외 처리 코드
        }
    }
    
}
```

<br>

**4. try-with-resource**
- 자바 7부터 사용 가능하다.
- `try(...)안에서 선언된 객체들에 대해 try가 종료 될때 자동으로 자원을 해체해주는 기능이다.`
- finally에서 close()를 명시적으로 호출해줄 필요가 없다.
- try-with-resources에서 자동으로 close가 호출되는 것은 `AutoCloseable`을 구현한 객체에만 해당 된다.
  - 커스텀한 클래스의 자원도 해체되길 원하면 AutoCloseable을 구현하면 된다.

```java
class Test {
  void resourceException(){
    try(BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));) {
        //실행 코드
    } catch (Exception e) {
      e.printStackTrace();
    }
  } 
}
```
- try문을 벗어나면 BufferedReader을 close()한다.
- 코드를 짧고 간결하게 만들어 읽기 쉽고, 유지보수가 쉬워진다.

<br>

**예외 처리 방법**

예외를 처리하는 방법에는 `예외 복구`, `예외 처리 회피`, `예외 전환` 방법이 있다.

**1. 예외 복구**
- 예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려 놓는 방법
  - Exception이 발생하여도 Application은 정상적으로 동작
- 예외를 잡아서 일정 시간, 조건만큼 대기하고 다시 재시도를 반복한다.
- 최대 재시도 횟수를 넘기게 되는 경우 예외를 발생시킨다.
```java
public void exception(){
        int maxRetry=10; // 재시도 횟수 10회

        while(maxRetry>0){
            try{
                // 이곳에 예외가 발생할 가능성이 있는 코드 작성 
                return; // 예외 없이 성공 시 리턴
            }catch(IOException e){
                // 예외에 대한 로그 출력, 정해진 시간 만큼 대기
                maxRetry--; // 재시도 횟수 감소
            }finally{
                // 리소스 반납 및 정리 작업
            }
        }
        // 최대 횟수 실패시 예외 Throw
        throw new MaxTryFailedException();
  }
```
<br>

**2. 예외 처리 회피**
- 예외 처리를 직접 담당하지 않고 호출한 쪽으로 던져 회피하는 방법
- 그래도 예외 처리의 필요성이 있다면 어느 정도는 처리하고 던지는 것이 좋다.
- 긴밀하게 역할을 분담하고 있는 경우 예외를 그냥 던지는 것은 무책임하다.

Exception을 회피하고 throw하는 것에 확신이 들 경우만 사용하는게 좋다.
```java
// 예시 1
public void add() throws SQLException {
    // ...생략
}
// 예시 2
public void add() throws SQLException {
    try {
        // ... 생략
    } catch(SQLException e) {
        // 로그를 출력하고 다시 날린다!
        throw e;
    }
}
```
<br>

**3. 예외 전환**
- 예외 회피와 비슷하게 메서드 밖으로 예외를 던지지만, 그냥 던지지 않고 적절한 예외로 전환해서 넘기는 방법
- 조금 더 명확한 의미로 전달되기 위해 적합한 의미를 가진 예외로 변경한다.
- 예외 처리를 단순하게 만들기 위해 포장(Wrap)할 수도 있다.
```java
// 조금 더 명확한 예외로 던진다.
public void add(User user) throws DuplicateUserIdException, SQLException {
    try {
        // ...생략
    } catch(SQLException e) {
        if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY) {
            throw DuplicateUserIdException();
        }
        else throw e;
    }
}
// 예외를 단순하게 포장한다.
public void someMethod() {
    try {
        // ...생략
    }
    catch(NamingException ne) {
        throw new EJBException(ne);
        }
    catch(SQLException se) {
        throw new EJBException(se);
        }
    catch(RemoteException re) {
        throw new EJBException(re);
        }
}
```
<br>

### 5. 커스텀한 예외 만드는 방법

- `Checked Exception`을 구현하기 위해서는 `Exception` 클래스를 상속받는다.
- `Unchecked Exception`을 구현하기 위해서는 `RuntimeException` 클래스를 상속받는다.

- 사용자 정의 예외 클래스 작성 시 생성자는 두 개를 선언하는 것이 일반적이다.
  - 매개 변수가 없는 기본 생성자
  - 예외 발생 원인(예외 메시지)을 전달하기 위해 String 타입의 매개변수를 갖는 생성자

```java
public class CustomException extends RuntimeException {

    // 기본 생성자
    CustomException() {

    }

    // 예외 메시지 전달하기 위한 생성자
    CustomException(String message) {
        super(message); // RuntimeException 클래스의 생성자를 호출
    }
}
```

### 예외 정보 얻기
- try 블록에서 예외가 발생되면 예외 객체는 catch 블록의 매개 변수에서 참조할 수 있다.
  - 이 매개변수로 예외정보 접근 가능.
- 모든 예외 객체는 Exception 클래스를 상속하기 때문에 Exception이 가지고 있는 메소드들을 모든 예외 객체에서 호출할 수 있습니다.
- Exception는 Throwable를 상속받고 Throwable에 객체의 정보를 얻을 수 있는 메소드를 가지고 있습니다.
- 주로 자주 사용되는 메소드는 `getMessage()`와 `printStackTrace()`입니다.

<br>

- getMessage()
  - 에러의 원인을 간단하게 출력
  - 발생한 예외클래스의 인스턴스에 저장된 메시지 출력
  - String 타입의 매개변수 메시지를 갖는 생성자를 이용하였다면, 메시지는 자동적으로 예외 객체 내부에 저장되게 되는데 이 메시지를 리턴하는 함수
  - 예외 메시지의 내용에는 왜 예외가 발생했는지에 대한 간단한 설명이 포함됩니다.

- printStackTrace()
  - 에러의 발생근원지를 찾아서 단계별로 에러를 출력한다.
  - 예외 발생 당시의 호출스택에 있었던 메서드 정보와 예외 메시지 출력
  - 많은 시스템 자원을 소모하므로 운영중엔 사용하지 않는다. 
  
